### ISSUE TITLE
Review of negative controls

### ISSUE THREAD

**Issue by chandryou** [ohdsi-studies/Eumaeus#3]
I worry that several negative outcomes below can be aggravated or started with systematic inflammation reaction caused by vaccination

Outcome Id | Outcome Name
-------- | ---------
443721|Sickle cell-hemoglobin C disease with crisis
200762 | Autoimmune hepatitis
438688 | Sarcoidosis
4308394| Infection and inflammatory reaction due to prosthetic device, implant and graft in urinary system

**Comment by schuemie** [comment]
I've removed these negative controls. Thanks!
